name: Feature Request
description: Brain power over 3000.
title: "[Feature Request]: "
assignees: misspent
labels: [enhancement]
body:
  - type: checkboxes
    id: check
    attributes:
      label: "🔍 Did you check former suggestions?"
      description: "Please make sure this hasn't been requested before. I will close this issue if it's a duplicate."
      options:
      - label: "I have checked and can't find anything to do with it"
        required: true
  - type: textarea
    id: plugin-feature
    attributes:
      label: "🔌 Is your feature request related to an extension/script you use?"
      description: "Which theme is it for(Nexus/YouTube)? What is the extension/script's name and link to the site"
      value: |
        Name of theme it's for: 
        The extension/script's name: 
        Link to the extension/script: 
      render: bash
  - type: textarea
    id: solution
    attributes:
      label: "📝 Describe what you want added"
      description: "In detail describe what it's, why you want it and how you think it'll improve this theme. Screenshots will be appreciated."
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: "➕ Something other than a extension/script request goes here"
      description: "Describe what you want in a clear and concise manner; drop the .class here if you can/know how to."
  - type: textarea
    id: screenshots
    attributes:
      label: "📸 Screenshots"
      description: "If applicable, add screenshots to help give me a bigger picture of the issue at hand (It'll be very convenient and helpful if you do)."
      render: bash
