name: Other
description: Imagination time.
title: "[Other]: "
assignees: misspent
labels: ["Channel Icon"]
body:
  - type: checkboxes
    id: check
    attributes:
      label: 🔍 Did you check former issues/requests?
      description: "Please check out other issues before continuing. I will close this issue if it's a duplicate."
      options:
      - label: "I have checked other issues"
        required: true
  - type: textarea
    id: solution
    attributes:
      label: "📝 Describe what you want"
      description: "In detail describe what it's, and why you want it."
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: "📸 Screenshots"
      description: "If applicable, add screenshots here, this will make everything easier for you and me."
      render: bash
  - type: textarea
    id: other
    attributes:
      label: "➕ More the merrier"
      description: "Off topic, redundant or something you didn't want in the description"
